export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN';
export const RESET_PASSWORD_SCREEN = 'RESET_PASSWORD_SCREEN';
export const OTP_SCREEN = 'OTP_SCREEN';
export const SUCCESS_MESSAGE_SCREEN = 'SUCCESS_MESSAGE_SCREEN';

export const HOME_SCREEN = 'HOME_SCREEN';
export const WITHDRAWAL_SCREEN = 'WITHDRAWAL_SCREEN';
export const DEPOSIT_SCREEN = 'DEPOSIT_SCREEN';
export const REFERRAL_TEAM_SCREEN = 'REFERRAL_TEAM_SCREEN';
export const TREE_STRUCTURE_SCREEN = 'TREE_STRUCTURE_SCREEN';
export const DEPOSIT_SUMMARY_SCREEN = 'DEPOSIT_SUMMARY_SCREEN';
export const BONUS_SUMMARY_SCREEN = 'BONUS_SUMMARY_SCREEN';
export const LEVEL_REPORT_SUMMARY_SCREEN = 'LEVEL_REPORT_SUMMARY_SCREEN';
export const ROI_INCOME_SUMMARY_SCREEN = 'ROI_INCOME_SUMMARY_SCREEN';
export const CASH_WALLET_SUMMARY_SCREEN = 'CASH_WALLET_SUMMARY_SCREEN';
export const WITHDRAWAL_SUMMARY_SCREEN = 'WITHDRAWAL_SUMMARY_SCREEN';

export const NEW_SUPPORT_SCREEN = 'NEW_SUPPORT_SCREEN';
export const SUPPORT_SUMMARY_SCREEN = 'SUPPORT_SUMMARY_SCREEN';

export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const EDIT_PROFILE_SCREEN = 'EDIT_PROFILE_SCREEN';
export const CHANGE_PASSWORD_SCREEN = 'CHANGE_PASSWORD_SCREEN';
export const CHANGE_ADDRESS_SCREEN = 'CHANGE_ADDRESS_SCREEN';
