export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN';
export const RESET_PASSWORD_SCREEN = 'RESET_PASSWORD_SCREEN';
export const OTP_SCREEN = 'OTP_SCREEN';
export const SUCCESS_MESSAGE_SCREEN = 'SUCCESS_MESSAGE_SCREEN';
